spring.application.name=Projeto2bi_FCIII
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ativooperante}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
